#pragma once

#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPING_FORCE_HOLD
#define PERMISSIVE_HOLD
// #define RETRO_TAPPING
// #define RETRO_TAPPING_PER_KEY