#pragma once

#define TAPPING_TERM 175
#define TAPPING_TERM_PER_KEY
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPING_FORCE_HOLD
#define PERMISSIVE_HOLD
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_NONE

// #ifdef RGB_MATRIX_ENABLE
// #	define RGB_BSTEEL	60, 90, 128
// #	define RGB_DGRAY	77, 77, 77
// #	define RGB_DEFAULT	RGB_BSTEEL
// #	define RGB_MODS		RGB_BSTEEL
// #	define RGB_CAPS		RGB_PURPLE
// #	define RGB_LAYER	RGB_DGRAY
// #	define HSV_DEFAULT	HSV_AZURE
// #	define HSV_SHIFT	HSV_YELLOW
// #endif

#ifdef RGB_MATRIX_ENABLE
#	define RGB_DISABLE_WHEN_USB_SUSPENDED true
#	define DISABLE_RGB_MATRIX_ALPHAS_MODS
#	define DISABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#	define DISABLE_RGB_MATRIX_BREATHING
#	define DISABLE_RGB_MATRIX_BAND_SAT
#	define DISABLE_RGB_MATRIX_BAND_VAL
#	define DISABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#	define DISABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#	define DISABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#	define DISABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#	define DISABLE_RGB_MATRIX_CYCLE_ALL
#	define DISABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#	define DISABLE_RGB_MATRIX_CYCLE_UP_DOWN
#	define DISABLE_RGB_MATRIX_CYCLE_OUT_IN
#	define DISABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#	define DISABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#	define DISABLE_RGB_MATRIX_DUAL_BEACON
#	define DISABLE_RGB_MATRIX_CYCLE_PINWHEEL
#	define DISABLE_RGB_MATRIX_CYCLE_SPIRAL
#	define DISABLE_RGB_MATRIX_RAINBOW_BEACON
#	define DISABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#	define DISABLE_RGB_MATRIX_RAINDROPS
#	define DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#	define DISABLE_RGB_MATRIX_TYPING_HEATMAP
#	define DISABLE_RGB_MATRIX_DIGITAL_RAIN
#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE
#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#	define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#	define DISABLE_RGB_MATRIX_SPLASH
#	define DISABLE_RGB_MATRIX_MULTISPLASH
#	define DISABLE_RGB_MATRIX_SOLID_SPLASH
#	define DISABLE_RGB_MATRIX_SOLID_MULTISPLASH
#endif

#ifdef MOUSEKEY_ENABLE
#	define MOUSEKEY_DELAY 0
#	define MOUSEKEY_INTERVAL 16
#	define MOUSEKEY_MAX_SPEED 7
#	define MOUSEKEY_TIME_TO_MAX 40
#	define MOUSEKEY_WHEEL_DELAY 0
#	define MOUSEKEY_WHEEL_INTERVAL 50
#	define MOUSEKEY_WHEEL_TIME_TO_MAX 100
#endif